# Generated by Django 4.1.4 on 2023-01-09 13:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pproperty_image', models.FileField(upload_to='property_image')),
                ('property_type', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('amenities', ckeditor.fields.RichTextField()),
                ('property_size', models.CharField(max_length=255)),
                ('no_of_bathrooms', models.PositiveBigIntegerField(default=0)),
                ('no_of_bedrooms', models.PositiveBigIntegerField(default=0)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_gallery_image', models.FileField(upload_to='property_gallery_image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='corporate.property')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
