# Generated by Django 4.1.4 on 2023-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_price',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
