# Generated by Django 4.1.4 on 2023-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_alter_agent_slug_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='no_of_rooms',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
