# Generated by Django 4.1.4 on 2023-01-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0011_agent_description_agent_email_agent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='corporate.agent'),
            preserve_default=False,
        ),
    ]
