# Generated by Django 4.1.4 on 2023-01-31 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0012_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='corporate.property'),
            preserve_default=False,
        ),
    ]
