# Generated by Django 4.1.4 on 2023-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0016_bookingidtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingidtracker',
            name='number',
            field=models.PositiveBigIntegerField(default=0, max_length=255),
        ),
    ]
