# Generated by Django 4.1.4 on 2023-02-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0018_delete_bookingidtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_booking', to='corporate.property'),
            preserve_default=False,
        ),
    ]
