# Generated by Django 4.1.4 on 2023-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0023_bookingidtracker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
