# Generated by Django 4.1.4 on 2023-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0025_customerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
