# Generated by Django 4.1.4 on 2023-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0026_booking_number_of_people_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_days',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
