# Generated by Django 4.1.4 on 2023-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0027_booking_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.FloatField(default=0.0),
        ),
    ]
