# Generated by Django 4.1.4 on 2023-02-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0029_booking_booking_status_checkoutcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info_booking_customer', to='corporate.customerinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_booking', to='corporate.property'),
        ),
    ]
