# Generated by Django 4.1.4 on 2023-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0030_remove_customerinfo_booking_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
