# Generated by Django 4.1.4 on 2023-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0033_generalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpage',
            name='name',
            field=models.CharField(choices=[('', 'Choose page name'), ('terms-and-conditions', 'Terms & Conditions'), ('about-us', 'About Us')], max_length=255),
        ),
    ]
