# Generated by Django 4.1.4 on 2023-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0035_rename_property_price_property_deluxe_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='deluxe_room',
            new_name='deluxe_room_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='deluxe_room_with_patio',
            new_name='deluxe_room_with_patio_price',
        ),
        migrations.AddField(
            model_name='property',
            name='standard_price',
            field=models.FloatField(default=0.0),
        ),
    ]
