# Generated by Django 4.1.4 on 2023-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0038_rename_booking_option_property_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='booking_options',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_options',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
